apiVersion: v1
kind: Service
metadata:
  # the name of that the worker app is looking for is bd
  # remember that services should be named based on what the other application is looking for
  # worker is looking for a service hostname db

  name: db
  labels:
    name: db-service
    app: demo-voting-app

spec:
  ports:
  - port: 5432
    targetPort: 5432

  # link this service to postgres pod
  # copy labels from postgres pod

  selector:
    name: postgres-pod
    app: demo-voting-app
