apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis-pod
    # All definitions for the same app have the same app name (all diff. pods)
    app: demo-voting-app
spec:
  containers:
  - name: redis
    image: redis:latest
    ports:
     - containerPort: 6379